import './global.css'

import type { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function Layout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html
      lang='ja'
      className='bg-mauve12 text-mauve1 dark:bg-mauve1 dark:text-mauve12'
    >
      <head />
      {children}
    </html>
  )
}
