import '../styles/globals.css'
import { Montserrat, Noto_Sans_JP } from 'next/font/google'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
  display: 'swap',
})

const notojp = Noto_Sans_JP({
  weight: ['400', '500'],
  subsets: ['latin'],
  variable: '--font-notojp',
  display: 'swap',
})

import type { Metadata } from 'next'

type RootLayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang='ja'>
      <head />
      <body className={`${montserrat.variable} ${notojp.variable}`}>
        {children}
      </body>
    </html>
  )
}
