import type { Metadata } from "next";
// eslint-disable-next-line camelcase
import { Montserrat, Noto_Sans_JP } from "next/font/google";
import "./globals.scss";

const montserrat = Montserrat({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-montserrat",
});
const notojp = Noto_Sans_JP({
  display: "swap",
  subsets: ["latin"],
  variable: "--font-notojp",
  weight: ["400", "500"],
});

type RootLayoutProps = {
  children: React.ReactNode;
};

export const metadata: Metadata = {
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
  title: "Create Next App",
};

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang="ja">
      <head />
      <body className={`${montserrat.variable} ${notojp.variable}`}>
        {children}
      </body>
    </html>
  );
}
