import '../styles/globals.css'

import type { Metadata } from 'next'

type RootLayoutProps = {
  children: React.ReactNode
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: '/favicon.ico',
  },
}

export default function RootLayout({ children }: RootLayoutProps): JSX.Element {
  return (
    <html lang='ja'>
      <head />
      <body>{children}</body>
    </html>
  )
}
